authorName: Unknown
experimentName: enas_macro
trialConcurrency: 2
maxExecDuration: 24h
maxTrialNum: 4
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
multiPhase: false
tuner:
  codeDir: ../tuner
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    macro_str: "macro"
    child_train_steps: 10
    controller_train_steps: 10

trial:
  command: sh ./script/macro_child.sh
  codeDir: ./
  gpuNum: 1

# machineList:
#   - ip: 10.150.144.121
#     username: v-zejlin
#     passwd: v-zejlin
