authorName: Unknown
experimentName: enas_macro
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 1
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
multiPhase: true
tuner:
  codeDir: ./src/cifar10
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    child_train_steps: 350
    controller_train_steps: 50

trial:
  command: sh ./macro_cifar10.sh
  codeDir: ./
  gpuNum: 1

