authorName: Unknown
experimentName: enas_macro
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 6
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
multiPhase: false
tuner:
  codeDir: ../tuner
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    child_train_steps: 2
    controller_train_steps: 1

trial:
  command: sh ./macro_cifar10.sh
  codeDir: ./
  gpuNum: 1

# machineList:
#   - ip: 10.150.144.121
#     username: v-zejlin
#     passwd: v-zejlin
