authorName: Unknown
experimentName: enas_macro
trialConcurrency: 2
maxExecDuration: 24h
maxTrialNum: 2
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
multiPhase: false
tuner:
  codeDir: .
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    batch_size: 2

trial:
  command: sh ./macro_cifar10_final.sh
  codeDir: ./
  gpuNum: 1

