authorName: default
experimentName: example_mnist
trialConcurrency: 3
maxExecDuration: 8888888h
maxTrialNum: 12
#choice: local, remote, pai
trainingServicePlatform: pai
#choice: true, false
useAnnotation: true
multiPhase: false
tuner:
  codeDir: .
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    batch_size: 3
trial:
  command: df -hT /dev/shm && python3 mnist.py
  codeDir: .
  gpuNum: 2
  cpuNum: 2
  memoryMB: 16392
  #The docker image to run nni job on pai
  image: zejlin/nni:ir
  dataDir: hdfs://10.151.40.179:9286/quzha
  outputDir: hdfs://10.151.40.179:9286/quzha
  virtualCluster: nni
paiConfig:
  userName: quzha
  passWord: quzha123
  host: 10.151.40.179