authorName: default
experimentName: example_mnist
trialConcurrency: 50
maxExecDuration: 8888888h
maxTrialNum: 80000
#choice: local, remote, pai
trainingServicePlatform: pai
#choice: true, false
useAnnotation: true
multiPhase: false
logDir: /data/v-zejlin/nni
nniManagerIp: 10.150.144.121
tuner:
  codeDir: .
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    batch_size: 50
trial:
  command: sh ./macro_cifar10_final.sh
  codeDir: .
  gpuNum: 1
  cpuNum: 2
  memoryMB: 16384
  #The docker image to run nni job on pai
  image: zejlin/nni:ir
  dataDir: hdfs://10.151.40.179:9286/quzha
  outputDir: hdfs://10.151.40.179:9286/quzha
  virtualCluster: nni
paiConfig:
  userName: quzha
  passWord: quzha123
  host: 10.151.40.179
