authorName: default
experimentName: example_mnist
trialConcurrency: 2
maxExecDuration: 1h
maxTrialNum: 4
#choice: local, remote, pai
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
tuner:
  codeDir: .
  classFileName: tuner.py
  className: NaiveTuner
trial:
  command: python3 trial.py
  codeDir: .
  gpuNum: 0
